
import * as Font from 'expo-font';


async function load() {
  await Font.loadAsync({
    'Poppins_medium': require('./assets/assets/fonts/Poppins_medium.ttf'),
    "DM_Sans_medium": require('./assets/assets/fonts/DM_Sans_medium.ttf'),
    "DM_Sans_regular": require('./assets/assets/fonts/DM_Sans_regular.ttf'),
    "DM_Sans_bold": require('./assets/assets/fonts/DM_Sans_bold.ttf'),
    "Roboto_bold": require('./assets/assets/fonts/Roboto_bold.ttf'),
    "Inter_semibold": require('./assets/assets/fonts/Inter_semibold.ttf'),
    "Inter_bold": require('./assets/assets/fonts/Inter_bold.ttf'),
    "Poppins_regular": require('./assets/assets/fonts/Poppins_regular.ttf'),
    "Inter_regular": require('./assets/assets/fonts/Inter_regular.ttf'),
    "Poppins_bold": require('./assets/assets/fonts/Poppins_bold.ttf'),
    "Poppins_semibold": require('./assets/assets/fonts/Poppins_semibold.ttf'),
    "Inter_medium": require('./assets/assets/fonts/Inter_medium.ttf'),
    "Inter_regular_italic": require('./assets/assets/fonts/Inter_regular_italic.ttf'),
    "Inter_extrabold": require('./assets/assets/fonts/Inter_extrabold.ttf'),
    "Plus_Jakarta_Sans_regular": require('./assets/assets/fonts/Plus_Jakarta_Sans_regular.ttf'),
    "Plus_Jakarta_Sans_bold": require('./assets/assets/fonts/Plus_Jakarta_Sans_bold.ttf'),
    "Plus_Jakarta_Sans_semibold": require('./assets/assets/fonts/Plus_Jakarta_Sans_semibold.ttf'),
    "Work_Sans_medium": require('./assets/assets/fonts/Work_Sans_medium.ttf'),
    "Work_Sans_regular": require('./assets/assets/fonts/Work_Sans_regular.ttf'),
    "Work_Sans_semibold": require('./assets/assets/fonts/Work_Sans_semibold.ttf'),
    "Work_Sans_bold": require('./assets/assets/fonts/Work_Sans_bold.ttf'),
  })
}

load();

/* fonts */
export const FontFamily = {
  poppinsMedium: "Poppins_medium",
  bodyMain: "DM_Sans_medium",
  captionSubdue: "DM_Sans_regular",
  subHeadlineMain: "DM_Sans_bold",
  robotoBold: "Roboto_bold",
  interSemibold: "Inter_semibold",
  interBold: "Inter_bold",
  poppinsRegular: "Poppins_regular",
  interRegular: "Inter_regular",
  poppinsBold: "Poppins_bold",
  poppinsSemibold: "Poppins_semibold",
  interMedium: "Inter_medium",
  interRegularItalic: "Inter_regular_italic",
  interExtrabold: "Inter_extrabold",
  plusJakartaSansRegular: "Plus_Jakarta_Sans_regular",
  plusJakartaSansBold: "Plus_Jakarta_Sans_bold",
  plusJakartaSansSemibold: "Plus_Jakarta_Sans_semibold",
  buttonTextCryptoFilled: "Work_Sans_medium",
  bodyTextCrypto: "Work_Sans_regular",
  subheading: "Work_Sans_semibold",
  workSansBold: "Work_Sans_bold",
};
/* font sizes */
export const FontSize = {
  size_xs: 12,
  bodyMain_size: 13,
  captionSubdue_size: 11,
  subHeadlineMain_size: 14,
  subheading_size: 20,
  size_mini_9: 15,
  size_base: 16,
  size_3xl_5: 23,
  size_mid_5: 18,
  size_base_3: 15,
  size_lgi_7: 20,
  size_lg: 18,
  size_7xl: 26,
  size_5xl: 24,
  size_13xl: 32,
  buttonTextCryptoFilled_size: 15,
  label_size: 10,
};
/* Colors */
export const Color = {
  white: "#fff",
  gray_100: "#fcfcfe",
  gray_200: "#868686",
  black1: "#182035",
  primaryBlack: "#181d27",
  gray_300: "#141415",
  gray_400: "rgba(0, 0, 0, 0.4)",
  gray_500: "rgba(0, 0, 0, 0.35)",
  gray_600: "rgba(255, 255, 255, 0.2)",
  gray_700: "rgba(0, 0, 0, 0.5)",
  grayDark: "#ababab",
  darkgray_100: "#a1a1a1",
  dimgray_100: "#5f5f63",
  primaryGray: "#555",
  grayVeryLight: "#e8e8e8",
  gainsboro_100: "rgba(217, 217, 217, 0)",
  midnightblue: "#161455",
  black: "#000",
  lime: "#00ff47",
  steelblue_100: "#016dab",
  steelblue_200: "rgba(1, 109, 171, 0.1)",
  lightslategray: "#9098a3",
  lightblue_100: "rgba(147, 186, 191, 0.75)",
  whitesmoke_100: "#f8f8f8",
  whitesmoke_200: "#f5f5f5",
  darkslateblue: "#273157",
  red_100: "#f81919",
  red_200: "#ff1111",
  red_300: "#ff0000",
  yellowgreen: "#61af2b",
  darkslategray_100: "#333",
  darkslategray_200: "#303030",
  text: "#2c2d2f",
  slategray: "#628093",
  lavenderblush: "#f8e8f8",
  lavender_100: "#e6eafa",
  lavender_200: "#dddaef",
  oldlace: "#fcf1e3",
  honeydew_100: "#eef7e8",
  honeydew_200: "#e0f8ef",
  mediumturquoise: "rgba(133, 215, 200, 0.75)",
  aliceblue: "#dcf0fb",
  deepskyblue: "rgba(87, 182, 235, 0.75)",
  cornsilk: "#fcf5dc",
  khaki: "rgba(225, 211, 80, 0.75)",
  plum: "rgba(188, 147, 191, 0.75)",
  primaryCrypto: "#2f80ed",
};
/* Paddings */
export const Padding = {
  p_3xs: 10,
  p_xs: 12,
  p_2xl_9: 22,
  p_4xs_8: 9,
  p_mid_5: 18,
  p_sm_1: 13,
  p_base_4: 16,
  p_13xl: 32,
  p_28xl: 47,
  p_xl: 20,
  p_10xs: 3,
  p_7xs: 6,
  p_9xs: 4,
};
/* border radiuses */
export const Border = {
  br_21xl: 40,
  br_13xl: 32,
  br_16xl: 35,
  br_41xl: 60,
  br_11xs_3: 1,
  br_10xs_7: 3,
  br_7xl_3: 26,
  br_5xl_8: 25,
  br_8xs_6: 5,
  br_81xl: 100,
  br_3xs: 10,
  br_29xl: 48,
  br_8xs: 5,
  br_11xl: 30,
  br_2xl_9: 22,
  br_mid_5: 18,
  br_5xs: 8,
  br_xs: 12,
  br_31xl: 50,
  br_5xl: 24,
};
